### PR TITLE
Update outdated urls

### PR DESCRIPTION
**Pull request by xyang76**
Some old URLs are outdated, I did small modifications so that "ant jar" command works.

### CODE REVIEW

**Review by kfirlevari — APPROVED** [review]
Thanks!

**Comment by xyang76** [comment]
Hi Kfir,

I am currently working in the consistency area, I have some questions after
learning your paper and your codes, could you please help me clarify them:
1. Section 4.2 "Our sync operation performs a dummy update", you said
zookeeper's sync is not linearizable, may I know where the zoonet sync code
is? Did you modify the zookeeper sync or add a new sync method?
2. Zookeeper is sequential read and linearizable write because of lagged
read, how does zoonet satisfy the linearizable requirement?
3. When I run "./bin/runZooNetSystest.sh", I get some socket error
messages, and your printout data seems not easy to read, could you please
help me figure them out? (See attachment)

Thank you,
Xincheng

**Comment by kfirlevari** [comment]
Hi Xincheng,
Sure, I'll try to clarify - 
1. From what I remember, ZooKeeper's sync wasn't a strong operation back then (I don't know if they change it since, and AFAIR we didn't change it as well), we simply used a dummy write (i.e., writing to a dummy pre-defined key) to simulate sync (we needed a strong operation, and didn't care much which).
2. That's a great question. We actually prove in a different paper, see https://webee.technion.ac.il/~idish/ftp/OSC-IPL17.pdf
3. Seems like the attachment was lost (at least I can't see it here). Can you reply directly on github? or send a link to the image and I'll try to help.

Cheers,
Kfir

**Comment by xyang76** [comment]
Great appreciate for your help!

Xincheng

**Comment by xyang76** [comment]
For question 3, I uploaded the image to the following link:

https://github.com/xyang76/ZooNet/blob/trunk/Screenshot%20from%202021-01-08%2011-43-32.png

Thank you very much!
Xincheng

**Comment by kfirlevari** [comment]
Let's try. 
So the batch test file has two main parts, in the first, we generate config files (via generateCfgs()), and the second runs tests, one for each config file (in runTests()). 
Seems like the prints related to the ZK instances, not to the metadata ZK that we create (in order to monitor the test IIRC).
So the relevant line from that file is java -jar $ZKJAR znSysTest "$CFGDir"/"$confNameWithExt", i.e., you should look at that zkSysTest code, and there you'll see how things behave. 
Specifically, for the prints, look at src/java/systest/org/apache/zookeeper/test/system/ZNSysTestReporterThread.java, line 168, where the report is created. 

Cheers,
Kfir

**Comment by xyang76** [comment]
Thanks a lot!

Xincheng

**Pull request merged**
